name: Code Lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.18.0'
      - name: Lint
        run: |
          make lint
