name: Code Lint

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Lint
        run: |
          make lint
          GO111MODULE=off go get github.com/kyoh86/looppointer/cmd/looppointer
          $(go env GOPATH)/bin/looppointer ./...
