name: Trivy scanner

on:
  workflow_dispatch:
  push:
    branches: [ master, 'release-**' ]
    paths:
      - '.github/workflows/trivy.yaml'
      - 'pkg/**.go'
      - '!pkg/azureclients/v2/**.go'
      - '!kubetest2-aks/**.go'
      - 'cmd/**.go'
      - 'go.*'
      - '!vendor/**'
  pull_request:
    branches: [ master, 'release-**' ]
    paths:
      - '.github/workflows/trivy.yaml'
      - 'pkg/**.go'
      - '!pkg/azureclients/v2/**.go'
      - '!kubetest2-aks/**.go'
      - 'cmd/**.go'
      - 'go.*'
      - '!vendor/**'
  schedule:
    - cron: '35 12 * * 4'
permissions:
  contents: read
jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Set up Go 1.x
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version-file: go.mod
          cache: true
        id: go
      - name: Build images
        run: |
          export TAG=${{ github.sha }}
          make build-ccm-image
          make build-node-image-linux-amd64

      - name: Run Trivy scanner CCM
        uses: aquasecurity/trivy-action@b43daad0c3c96202fc5800b511dfae8e6ecce864 # master
        with:
          image-ref: 'local/azure-cloud-controller-manager:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-ccm-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
        with:
          sarif_file: 'trivy-ccm-results.sarif'
          category: azure-cloud-controller-manager-image
      - name: Run Trivy scanner CNM
        uses: aquasecurity/trivy-action@b43daad0c3c96202fc5800b511dfae8e6ecce864 # master
        with:
          image-ref: 'local/azure-cloud-node-manager:${{ github.sha }}-linux-amd64'
          format: 'sarif'
          output: 'trivy-cnm-linux-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.13.4
        with:
          sarif_file: 'trivy-cnm-linux-results.sarif'
          category: azure-cloud-node-manager-linux-image

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@b43daad0c3c96202fc5800b511dfae8e6ecce864 # master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'github'
          output: 'dependency-results.sbom.json'
          image-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}